### ISSUE TITLE
[PROPOSAL/TASK:] Opinionated creation of project tree

### ISSUE THREAD

**Issue by ByteOtter** [ByteOtter/nester#29]
# You would like to suggest a new feature?

It was brought to my attention that some users may prefer to have the dummy files that Nester creates pre-populated with real data. Such as the `pyproject.toml` or something similar.

This would require to expand the `create` function and make assumptions about several aspects. Such as the preferred build system etc.

Staying with python as an example:<br>
The user could do something like this `nester create -o py projectname setuptools` which then pre-populates the `pyproject.toml` like this:

```toml
[build-system]
requires = ["setuptools", "setuptools-scm", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "projectname"

[tool.setuptools_scm]
root = "."
relative_to = "src/projectname/__init__.py"

### etc ###
```
Would be interesting to see if, while we are doing this anyway, could let `pip install` the preferred build system in the background.

This would maybe also include other files.

It would also be interesting to see if we could integrate the popular [Poetry](https://python-poetry.org/) utility. Though this may be out of scope, as it does much more than just building.
